spring.data.mongodb.uri=mongodb+srv://farida5:55555@mellocluster.ap1kana.mongodb.net/?appName=MelloCluster
spring.data.mongodb.database=mello_db
server.port=8080
# Listen on all network interfaces so other machines on the same network can connect
server.address=0.0.0.0

# Gmail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mellohealthsupport@gmail.com
spring.mail.password=pfmfscxjuxcvfbag
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Increase payload limits for profile pictures (base64)
server.tomcat.max-http-post-size=10MB
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false